# stage1 - build react app first
FROM node:lts as build
WORKDIR /app

ENV REACT_APP_GRAPHQL_URL http://localhost:4000/graphql
ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json /app/
COPY ./package-lock.json /app/
RUN npm install

COPY . /app
RUN npm run build

# stage 2 - build the final image and copy the react build files
FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]